### ISSUE TITLE
How to access the ATM

### ISSUE THREAD

**Issue by supaflange** [BUBUSTEIN13/butons-money-mod#3]
Hi I was wondering how the ATM can be crafted or found. I don't see a recipe in JEI.

**Comment by BUBUSTEIN13** [comment]
ATM will be added in the next update. Now are available only creative banknotes. no recipes

**Comment by BUBUSTEIN13** [comment]
I hadn't enough time to work on this mod. I think the next update will be uploaded until 31 August.

**Comment by BUBUSTEIN13** [comment]
https://modrinth.com/mod/buton-money/version/0.2+1.20

https://modrinth.com/mod/buton-money/version/0.2+1.19.4

In this update, you can see the recipes.

I hope the next update will add the ATM
